apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: springboot
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      application: springboot
  template:
    metadata:
      labels:
        application: springboot
    spec:
      containers:
      - name: springboot
        image: tcs-icpdemo.icp:8500/default/springboot:rest
        ports:
        - containerPort: 8080
          protocol: TCP