apiVersion: v1
kind: Service
metadata:
  labels:
    application: aspnet
  name: aspnet
spec:
  selector:
    application: aspnet
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080