apiVersion: v1
kind: Service
metadata:
  labels:
    application: springboot
  name: springboot
spec:
  selector:
    application: springboot
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080